# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 281981b94b74b845b04e9838da9e2102e1b02cb78b3fe8e5f89586396ce782f2fa52c417fb79e73e3fb44893e9950b48d06d9c18f533fdb4fd4bc94182455ec9

test:
  secret_key_base: a655ab3a3b4cd0f891609aaf7a613ea07fc774222fa564d7f461954f3208dd41f0a6f37e5a248fbf462bb8a53de254a4eb420644b1a0ca39cdb2b4d1c6010c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
